name: Fast Linux RDP (Stable Tunnel)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install Desktop Environment & XRDP
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp
        
        # User & Password setup
        sudo useradd -m -s /bin/bash rdpuser
        echo "rdpuser:pass123" | sudo chpasswd
        sudo usermod -aG sudo,xrdp rdpuser
        
        # Session setup
        echo "startxfce4" | sudo tee /home/rdpuser/.xsession
        sudo chown rdpuser:rdpuser /home/rdpuser/.xsession
        
        # Fix XRDP Security Restrictions
        sudo sed -i 's/allowed_users=console/allowed_users=anybody/g' /etc/X11/Xwrapper.config
        sudo systemctl restart xrdp

    - name: Start Pinggy RDP Tunnel
      run: |
        echo "=========================================="
        echo "USERNAME     : rdpuser"
        echo "PASSWORD     : pass123"
        echo "=========================================="
        
        # Loop for continuous connection
        while true; do
          ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=15 -R 0:localhost:3389 tcp.pinggy.io
          echo "Tunnel disconnected. Reconnecting in 5 seconds..."
          sleep 5
        done
